version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
        environment:
          SECRET_KEY: abcd
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run: mkdir test # For xunit
      - run: python3 -m venv .venv
      - run: .venv/bin/pip install -r docker/requirements.txt
      - run: .venv/bin/pip install -e .[dev,standalone]
      - run: .venv/bin/pomodoro test
      - store_test_results:
          path: dist/test-results
      - store_artifacts:
          path: dist

general:
  branches:
    ignore:
      - gh-pages
